# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x06schema\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x01\n\x07Request\x12\x11\n\tpr_number\x18\x01 \x01(\x05\x12\x10\n\x08repo_url\x18\x02 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x03 \x01(\t\x12\x13\n\x0b\x63ommit_hash\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\r\n\x05title\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x08 \x01(\t\x12\r\n\x05\x65mail\x18\t \x01(\t2S\n\x12PullRequestService\x12=\n\x12ProcessPullRequest\x12\x0f.schema.Request\x1a\x16.google.protobuf.EmptyB0Z.github.com/sathwik/PatchForge/core/grpc;schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/sathwik/PatchForge/core/grpc;schema'
  _globals['_REQUEST']._serialized_start=54
  _globals['_REQUEST']._serialized_end=226
  _globals['_PULLREQUESTSERVICE']._serialized_start=228
  _globals['_PULLREQUESTSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
